USE airvoydb;

DROP TABLE IF EXISTS Users, Markets, Orders, Trades;

CREATE TABLE Users(Username VARCHAR(20) PRIMARY KEY, Balance DOUBLE, CreationTime BIGINT);
CREATE TABLE Markets(Id BIGINT PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(100), Expiry BIGINT, CreationTime BIGINT);
CREATE TABLE Orders(Id BIGINT PRIMARY KEY AUTO_INCREMENT, Type VARCHAR(20), Price DOUBLE, Amount DOUBLE, OrderTime BIGINT);
CREATE TABLE Trades(Id BIGINT PRIMARY KEY AUTO_INCREMENT, Maker VARCHAR(20), Taker VARCHAR(20), Price DOUBLE, Amount DOUBLE, Fee DOUBLE, TradeTime BIGINT);
